/*
** IRCIT Copyright (c) 1998 Ayman Akt
**
** This file is part of the IRCIT (c) source distribution.
** See the COPYING file for terms of use and conditions.
**
** Generated by CMake -- do not edit.
*/

char *t_compiled="Thu Jul 02 2026 at 12:40:57";
char *u_compiled="devops@AYmAN-XPS17";
