
 Event IRCITEvents[]=
 {
  {EVNT_STARTUP,     "STARTUP",     NULL, NULL, 0, 0},
  {EVNT_SERVERUP,    "SERVERUP",    NULL, NULL, 1, 0},
  {EVNT_SERVERDOWN,  "SERVERDOWN",  NULL, NULL, 1, 0},
  {EVNT_ODDSRVCMND,  "ODDSRVCMND",  NULL, NULL, 2, 0},
  {EVNT_CHANJOIN,    "CHANJOIN",    NULL, NULL, 3, 0},
  {EVNT_CHANUSRJOIN, "CHANUSRJOIN", NULL, NULL, 3, 0},
  {EVNT_CHANPART,    "CHANPART",    NULL, NULL, 3, 0},
  {EVNT_CHANUSRPART, "CHANUSRPART", NULL, NULL, 3, 0},
  {EVNT_CHANPRIVMSG, "CHANPRIVMSG", NULL, NULL, 3, 0},
  {EVNT_USRPRIVMSG,  "USRPRIVMSG",  NULL, NULL, 2, 0},
  {EVNT_TOPIC,       "TOPIC",       NULL, NULL, 3, 0},
  {EVNT_NICKCHANGE,  "NICKCHANGE",  NULL, NULL, 3, 0},
  {EVNT_INVITE,      "INVITE",      NULL, NULL, 3, 0},
  {EVNT_CHANCTCP,    "CHANCTCP",    NULL, NULL, 3, 0},
  {EVNT_USRCTCP,     "USRCTCP",     NULL, NULL, 3, 0},
  {EVNT_CHANKICK,    "CHANKICK",    NULL, NULL, 3, 0},
  {EVNT_CHANUSRKICK, "CHANUSRKICK", NULL, NULL, 3, 0}
 };

